<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	<TargetFrameworks>net6.0;net8.0;net10.0</TargetFrameworks>    
    <BaseOutputPath>..\bin\</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AnyCAD.Foundation.NET" Version="2026.1.1.1401" />
    <PackageReference Include="AnyCAD.Simulate.NET" Version="2026.1.1.1401" />
	  <PackageReference Include="AnyCAD.PointCloud.NET" Version="2026.1.1.1401" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

</Project>
